const wechat = {
    //设置剪贴板内容
    setClipboardData(obj){
      return new Promise((resolve,reject)=>{
        wx.setClipboardData({
            data:obj,
            success:function(res){
                console.log('剪贴板内容设置成功');
                console.log(res);
                resolve(true);
            },
            fail:function(res){
                console.log('剪贴板内容设置失败');
                console.log(res);
                resolve(false);
            }
        })
      });
    },
    getClipboardData(){
        return new Promise((resolve,reject)=>{
            wx.getClipboardData({
                success:function(res){
                    resolve(res.data);
                },
                fail:function(){
                    resolve("");
                }
            })
          });
    },
    navigateTo(data){
        wx.navigateTo(data);
    },
    navigateBack(data){
        wx.navigateBack(data);
    },
    switchTab(data){
        wx.switchTab(data);
    },
    getSetting(){
        return new Promise((resolve,reject)=>{
            wx.getSetting({
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    resolve(null);
                }
            })
          });
    },
    getUserInfo(){
        return new Promise((resolve,reject)=>{
            wx.getUserInfo({
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    resolve(null);
                }
            })
          });
    },
    login(){
        return new Promise((resolve,reject)=>{
            wx.login({
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    resolve(null);
                }
            })
          });
    },
    getStorageSync(key){
       return wx.getStorageSync(key);
    },
    setStorageSync(key,value){
        wx.setStorageSync(key,value);
    },
    navigateToMiniProgram(param){
        return new Promise((resolve,reject)=>{
            wx.navigateToMiniProgram({
                appId:param.appId,
                path:param.path,
                extraData:param.extraData,
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    reject(null);
                }
            })
          });
    },
    setNavigationBarTitle(title){
        return new Promise((resolve,reject)=>{
            wx.setNavigationBarTitle({
                title:title,
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    reject(null);
                }
            })
          });
    },
    pageScrollTo(param){
        wx.pageScrollTo(param);
    },
    getSystemInfo(){
        return new Promise((resolve,reject)=>{
            wx.getSystemInfo({
                success:function(res){
                    resolve(res);
                },
                fail:function(){
                    reject(null);
                }
            })
          });
    },
    //title,icon,duration
    showToast(param){
      wx.showToast(param);
    }
}

export {wechat as client};